### ISSUE TITLE
Inaccessible formatting

### ISSUE THREAD

**Issue by workingjubilee** [WebAssembly/spec#1608] opened 2023-02-19 22:21 UTC
The way that the spec is presented in the HTML format uses enormously inaccessible pseudo-text ("MathJax") instead of characters, even where characters would suffice e.g. when presenting largely tabular-formatted data. I cannot meaningfully use highlighting, computer-assisted search, etc. It makes it actively painful to navigate, read, understand, comment on, etc. I often highlight text in order to help read it as it creates contrast, or simply to copy, paste, reslice, examine, etc. And I do not find the accessibility features provided by MathJax to be sufficient, nor do they seem to actually work meaningfully with the presentation here.

It should be noted that I can deploy all of these approaches on artifacts like the Intel Software Development Manual and ISO C Standard even though they have, in spots, very nice formatting. I have in fact read many specifications for how software should execute or datasheets on how a machine should operate, and the WebAssembly spec is exceptional amongst all of them.

**Comment by rossberg** [comment] 2023-02-21 10:57
Closing as duplicate of #1515.

**Closed by rossberg** 2023-02-21 10:57 UTC
