### ISSUE TITLE
No mathdef Module found!

### ISSUE THREAD

**Issue by vmlite** [WebAssembly/spec#1100] opened 2019-11-15 15:05 UTC
I want to complier the document use sphinx ,but the mathdef Module missing.

I use pip and easy_install try to install it, but failed!

Oh!, I want to know how do you do it !.

Thanks!

**Comment by rossberg** [comment] 2019-11-15 15:55
Duplicate of #1075. This was a breaking change in Sphinx, you'll probably need to downgrade it to v1.7 for the time being. Patches welcome. :)

**Closed by rossberg** 2019-11-15 15:55 UTC
