### ISSUE TITLE
should grow_memory ever trap?

### ISSUE THREAD

**Issue by lukewagner** [WebAssembly/spec#334] opened 2016-09-05 21:17 UTC
AstSemantics.md does not describe [`grow_memory`](https://github.com/WebAssembly/design/blob/master/AstSemantics.md#resizing) as trapping.  However, `GrowMemory` traps in [two cases](https://github.com/WebAssembly/spec/blob/master/ml-proto/spec/eval.ml#L288) and there is a [test](https://github.com/WebAssembly/spec/blob/master/ml-proto/test/memory_trap.wast#L36) for this.  I think the trap and test predate `grow_memory` returning -1 on error and, now that it does, it'd be better to always return -1 instead of trapping.  That way the caller doesn't have to check for two separate error conditions.

**Comment by titzer** [comment] 2016-09-06 08:03
On Mon, Sep 5, 2016 at 11:17 PM, Luke Wagner <notifications@github.com>
wrote:

> AstSemantics.md does not describe grow_memory
> <https://github.com/WebAssembly/design/blob/master/AstSemantics.md#resizing>
> as trapping. However, GrowMemory traps in two cases
> <https://github.com/WebAssembly/spec/blob/master/ml-proto/spec/eval.ml#L288>
> and there is a test
> <https://github.com/WebAssembly/spec/blob/master/ml-proto/test/memory_trap.wast#L36>
> for this. I think the trap and test predate grow_memory returning -1 on
> error and, now that it does, it'd be better to always return -1 instead of
> trapping. That way the caller doesn't have to check for two separate error
> conditions.
>

Agreed.

**Comment by rossberg-chromium** [comment] 2016-09-06 09:03
This is a duplicate of #307. I fixed it a while ago in #308, but only on the 0xc branch, because the patch did not apply cleanly on master. I'll give it another shot to merge it back.

**Comment by rossberg-chromium** [comment] 2016-09-06 09:46
OK, done.

**Closed by rossberg-chromium** 2016-09-06 09:46 UTC

**Comment by lukewagner** [comment] 2016-09-06 13:38
Oops, thanks.
