### ISSUE TITLE
Questionable 'arity mismatch'

### ISSUE THREAD

**Issue by JSStats** [WebAssembly/spec#223] opened 2016-02-01 03:21 UTC
This example fails with a 'arity mismatch' in the ml-proto. It is accepted by sexp-wasm.

```
(module
 (func $f1 (result i32)
   (block $l0
     (br_if (i32.const 1) $l0
       (block $l1
         (br $l1 (i32.const 1))))
     (i32.const 1))))
```

**Comment by rossberg-chromium** [comment] 2016-02-02 00:12
This is an inverse-duplicate of #179. Please reopen that if you disagree with the resolution.

**Closed by rossberg-chromium** 2016-02-02 00:12 UTC
