### ISSUE TITLE
[test] Integrating spec tests into Web Platform Tests

### ISSUE THREAD

**Issue by titzer** [WebAssembly/spec#529] opened 2017-07-25 13:04 UTC
It's great that the spec test harness matches the Web Platform Test harness. Could we go the extra step and import these tests (exactly how TBD) to be periodically checked into the main Web Platform Test repository (https://github.com/w3c/web-platform-tests)?

**Comment by flagxor** [comment] 2017-07-26 08:06
Is there any appetite for moving the source of truth there eventually?
Are you'all running Web Platform Tests against your engines at the right point to catch regressions if that was the primary place they were run?

**Comment by lukewagner** [comment] 2017-07-26 14:24
I still need to learn more about how the overall system works and how tests flow in/out, but on its face, yeah, that makes sense.

**Comment by titzer** [comment] 2017-07-27 08:46
My personal opinion is that we should keep the source of truth for core WASM tests (i.e. wast tests) here in the spec repo. For JS API tests, I would strongly prefer to keep them here as well. For Web platform integration tests (i.e. the html/ directory here) I would slightly prefer to keep them here, but could be convinced otherwise.

**Comment by rossberg-chromium** [comment] 2017-07-27 09:54
+1. We should optimise for making the process of adding tests and creating
proposals simple and uniform, because that has the best chance of
encouraging as many tests as possible. It would be infeasible from my
perspective to move the 95% of (web-agnostic) core Wasm tests away from the
spec and the reference interpreter that is used to process them. And given
that, it seems to make most sense to keep the other tests here as well.

**Comment by lukewagner** [comment] 2017-07-27 17:52
Definitely agreed for core and JS (shell) tests staying in the spec repo.

**Comment by littledan** [comment] 2017-10-09 16:24
It's great to see so much attention to testing and encouraging the most welcoming environment for adding tests. This makes me really optimistic about the Wasm feature development process.

I think a two-way sync system could help with these goals. This technique has been used successfully in web-platform-tests for Chrome and Mozilla. With two-way sync, you can check in a change to tests either in an implementation repository, or in the upstream repository, and all repos are automatically synchronized with each other very frequently.

It looks like V8 currently maintains Wasm spec tests by pulling down a compressed archive, and in the SpiderMonkey source tree, I see generated tests in JavaScript which are based on the Wasm spec tests with a minimal wrapper template. Both of these processes seem to be "one way"--you add tests upstream, and then periodically pull them down. With either of these processes, I don't see a way that you can easily make a single patch which, e.g., fixes a bug, and in the same patch adds a regression test. It would be great if regression tests, added in a light-weight way, could be shared between implementations.

What would you think about using two-way sync for Wasm tests?

If we have two-way sync, maybe it would make sense to take advantage of web-platform-tests' infrastructure, or, maybe it would make sense to build parallel infrastructure. That's a narrower technical question; I wanted to talk about the project goals first.

cc @mjzffr @jgraham

**Comment by foolip** [comment] 2017-10-09 21:20
I just posted a few things in https://github.com/tc39/test262/issues/1258#issuecomment-335291387 that might be of interest to anyone considering the merits of two-way sync. To extract the two links:
 * [Blink WPT Sync Workflow](https://docs.google.com/document/d/16Si_dNF-Ot3-Fcfe_ny9d_GCLcNNmW9rRJ9SQmCA3T4/edit?usp=sharing) (WIP documentation by @Hexcles)
 * [Has two-way sync increased contributions? Yes!](https://groups.google.com/a/chromium.org/d/msg/ecosystem-infra/yDAnUCUqFcw/sk5gxzjbBgAJ) (showing a tripling of Chromium contributions)

**Comment by jgraham** [comment] 2017-10-10 07:32
> We should optimise for making the process of adding tests and creating proposals simple and uniform, because that has the best chance of encouraging as many tests as possible. 

I strongly agree with this premise.

> It would be infeasible from my perspective to move the 95% of (web-agnostic) core Wasm tests away from the spec and the reference interpreter that is used to process them. And given that, it seems to make most sense to keep the other tests here as well.

From my "generic" (i.e. without being focused on wasm specifically) browser-vendor perspective, I would come to the exact opposite conclusion. Keeping tests with a spec is a local optimum for people directly working on that spec. But there is evidence (for example in @foolip's comment above) that having a central repository for testing that allows vendors to contribute to, run, and sync, tests across the entire platform in a uniform way is more effective in getting vendors to contribute to the tests and to run an up-to-date copy of the testsuite.

Yes, in some ideal world we might be able to create a uniform contribution and sync pipeline that worked across multiple test repositories. But that isn't the world we live in. On the other hand, I expect we could solve technical issues around wasm in wpt specifically is there's some need to e.g. run travis jobs that depend on something in the spec repo. I don't know what the current setup you have is, so it's hard to make specific technical promises, but it certainly seems to me to be worth looking at the detailed requirements and assessing them for feasibility.

**Comment by rossberg-chromium** [comment] 2017-10-10 19:33
>
> From my "generic" (i.e. without being focused on wasm specifically)
> browser-vendor perspective, I would come to the exact opposite conclusion.
> Keeping tests with a spec is a local optimum for people directly working on
> that spec.
>

It also is the easier solution for most producers and for all consumers
that do not happen to be browser vendors. As misleading as the choice of
name may be, keep in mind that WebAssembly is explicitly designed and
specified to not be a browser-exclusive technology and that it might
potentially have more customers outside the Web (and JavaScript) ecosystem
than inside.

**Comment by littledan** [comment] 2017-10-10 21:44
Let's separate the two questions of two-way sync or no, and putting in the web-platform-tests repository or no. I definitely share your goal of including non-Web implementations of WebAssembly, including the reference interpreter.

For the two-way sync question, I don't have a clear understanding of how two-way sync would make things harder for non-web users, or less clean or pure, or anything like that. Could you explain more? cc @titzer who expressed similar concerns.

If we decide on two-way sync, for the choice of the main repository which everyone syncs to and from, as long as we make sure that the tests are in a format usable by non-web consumers, I'm not sure what the difference would be between any repository and any other. We could use the spec repository, or web-platform-tests. web-platform-tests might be easier because infrastructure is already there, but I don't see why that technical choice would make things any more tied to the web.

For proposals to include tests, in test262, we upstream tests that are for features that aren't yet at Stage 4, but with metadata that test users can use to switch the tests on or off, or pass runtime flags to turn the experimental features on for that subset of tests. One difficulty is making single patch which both specifies the change and adds tests--maybe we could set up two-way between the proposal repository as well, if that is a requirement.

**Comment by littledan** [comment] 2017-10-11 08:09
BTW another tweak we could make, if we want the spec repository to have a clean set of tests that's not dirtied by other implementations' tests, is do one-way sync from the spec repository into wpt, and put a lint in other wpt contributors to not edit those tests.

**Comment by rossberg-chromium** [comment] 2017-10-11 08:52
@littledan, yes, that's the alternative that we have been discussing (unfortunately, much of these discussions have been fairly scattered around).

**Comment by littledan** [comment] 2017-10-11 09:43
Sorry for repeating what was already discussed. If you have any pointers to past discussion, that would be helpful.

**Comment by foolip** [comment] 2017-10-13 08:09
I commented on the framing of the agenda in https://github.com/WebAssembly/meetings/pull/80, but @jfbastien suggested I paste it here instead:

To clarify "the WPT effort would like to incorporate as many WASM tests as possible": while tests for any web-exposed features are welcome in WPT, it's not a goal to subsume all other test suites, what matters is that shared test suites exist, are well maintained, and that there's good infrastructure around them.

I have no involvement in wasm, but I think these are the important questions:
 1. Would implementers like to add/change shared tests together with their code changes? (IMHO, this is very important, as otherwise using shared tests always comes with an overhead. See [this email](https://groups.google.com/a/chromium.org/d/msg/ecosystem-infra/yDAnUCUqFcw/sk5gxzjbBgAJ) for how much of a difference it seems to make.)
 1. If yes, how do you enable two-way sync between the repos involved?
 1. How do you get an always-fresh view of the state of the test suite, by which implementers can prioritize their work?

If merging into wpt and using wpt.fyi is the best answer, that'd be OK, and I don't anticipate you'd meet with any resistance. The build step could perhaps happen at runtime, looks like it's a [python script](https://github.com/WebAssembly/spec/blob/master/test/core/run.py) already.

As for a one-way sync in order to get results into wpt.fyi, someone would need to keep that always running and make sure that the special directory can't be changed in wpt and that people can immediately discover why. A separate wasm.fyi would feel cleaner, but that's a lot of work.

It would be nice if the outcome is all wasm tests in one place, not split over [spec/test](https://github.com/WebAssembly/spec/tree/master/test) and [wpt/wasm](https://github.com/w3c/web-platform-tests/tree/master/wasm) as currently.

**Comment by foolip** [comment] 2017-10-13 10:41
> The build step could perhaps happen at runtime

Perhaps I'll make that a bit stronger. I think that if you want to one-way sync into wpt, it should probably be done with git subtree, preserving the commit history, and making no modifications. If the wasm repo can be free of generated files and easy to understand, then so should a mirror of it.

**Comment by littledan** [comment] 2017-10-13 13:08
Concretely, since @foolip has explained a way within wpt to get around the technical limitations that were discussed before, it seems like this suggests two polls for the Wasm group:

1. Should there be two-way sync to maintain Wasm tests and implementers' tests from their own repositories, to lower the overhead to add more tests?
1. Should Wasm tests be moved to the wpt repository as the "source of truth"?

It sounds to me like all four combinations are technically possible.

**Comment by flagxor** [comment] 2017-10-16 18:32
I believe polls currently in the agenda ask effectively the same questions in reverse:
POLL: Tests contributed to the WASM spec repo should receive review from core contributors.
POLL: WASM should maintain the source of truth by having compliance tests in the spec repo, as today.

We can surely tweak that wording as the discussion progresses.

The first one being equivalent might not be obvious. It flows from the observation that 2 way sync requires the possibility that changes can flow into whatever the source of truth for the tests are, potentially without review from a core wasm contributor.
I suppose if 2-way sync infrastructure also had OWNERS like access controls, that might address the concern.

**Comment by jgraham** [comment] 2017-10-16 20:35
With that wording at least, I'm sure you will get agreement to do those things since it's of the form "we should continue to do <good sounding thing>". Hopefully the actual discussion is more balanced and mentions the tradeoffs implied by making the WASM tests a special case compared to other tests for web platform features.

**Comment by Ms2ger** [comment] 2019-01-25 11:55
This is done, fwiw.

**Comment by binji** [comment] 2019-01-25 16:45
Great! Let's close this issue.

**Closed by binji** 2019-01-25 16:45 UTC
