### ISSUE TITLE
mathjax: you can't use 'macro parameter character #' in math mode with the SVG renderer

### ISSUE THREAD

**Issue by nagisa** [WebAssembly/spec#1509] opened 2022-07-27 11:18 UTC
When MathJax is set to use the SVG renderer, loading a new page will fail to render any math blocks with the following message:

![You can't use 'macro parameter character #' in math mode](https://user-images.githubusercontent.com/679122/181233822-944dda77-7cd1-402f-a154-391e2ff808e1.png)

To reproduce:

1. Open any specification page with maths in it;
2. Right-click on one of the math blocks, select “Math Settings > Math Renderer > SVG”
3. Reload the page.

This is on Firefox 103.0a1, but appears to be reproducible on Chromium as well. The SVG renderer works if I select SVG renderer after the maths have already been rendered with CHTML.

It is critical for me that the SVG renderer works in order to avoid this issue: https://github.com/mathjax/MathJax/issues/2904

**Comment by rossberg** [comment] 2022-08-04 08:28
I'm not sure what's going on, but I can neither reproduce this on Chrome (104) nor on Safari (15.4). Closing, since this appears to be either a MathJax or a Firefox issue.

**Closed by rossberg** 2022-08-04 08:28 UTC
