### ISSUE TITLE
make wast.js => Error: missing module: wasm but make, make opt, make test, make all, make land are OK

### ISSUE THREAD

**Issue by CarpeDiemKopi** [WebAssembly/spec#1056] opened 2019-08-14 21:25 UTC
windows 10   CygWin64 

**After the following redesign of** 
`D:\Development\OCaml\spec\interpreter\meta\jslib\build.sh`

```
74 BWPTH="c:/Program Files/nodejs/node_modules/bs-platform/lib/js"
75 BUPTH="$(cygpath -u "${BWPTH}")"
76 bsb -init test || exit 1
77 # copy:
78 mkdir -p lib/js/src && cp "$BUPTH"/*.js lib/js/src
```

**the next bug comes now:**
```
copy /*.js lib/js/src
==== Linking full version ====
Logging on
Including lib/js/src/arg.js
Including lib/js/src/array.js
Including lib/js/src/arrayLabels.js
Including lib/js/src/belt.js
Including lib/js/src/belt_Array.js
Including lib/js/src/belt_Debug.js
Including lib/js/src/belt_Float.js
Including lib/js/src/belt_HashMap.js
Including lib/js/src/belt_HashMapInt.js
Including lib/js/src/belt_HashMapString.js
Including lib/js/src/belt_HashSet.js
Including lib/js/src/belt_HashSetInt.js
Including lib/js/src/belt_HashSetString.js
Including lib/js/src/belt_Id.js
Including lib/js/src/belt_Int.js
Including lib/js/src/belt_internalAVLset.js
Including lib/js/src/belt_internalAVLtree.js
Including lib/js/src/belt_internalBuckets.js
Including lib/js/src/belt_internalBucketsType.js
Including lib/js/src/belt_internalMapInt.js
Including lib/js/src/belt_internalMapString.js
Including lib/js/src/belt_internalSetBuckets.js
Including lib/js/src/belt_internalSetInt.js
Including lib/js/src/belt_internalSetString.js
Including lib/js/src/belt_List.js
Including lib/js/src/belt_Map.js
Including lib/js/src/belt_MapDict.js
Including lib/js/src/belt_MapInt.js
Including lib/js/src/belt_MapString.js
Including lib/js/src/belt_MutableMap.js
Including lib/js/src/belt_MutableMapInt.js
Including lib/js/src/belt_MutableMapString.js
Including lib/js/src/belt_MutableQueue.js
Including lib/js/src/belt_MutableSet.js
Including lib/js/src/belt_MutableSetInt.js
Including lib/js/src/belt_MutableSetString.js
Including lib/js/src/belt_MutableStack.js
Including lib/js/src/belt_Option.js
Including lib/js/src/belt_Range.js
Including lib/js/src/belt_Result.js
Including lib/js/src/belt_Set.js
Including lib/js/src/belt_SetDict.js
Including lib/js/src/belt_SetInt.js
Including lib/js/src/belt_SetString.js
Including lib/js/src/belt_SortArray.js
Including lib/js/src/belt_SortArrayInt.js
Including lib/js/src/belt_SortArrayString.js
Including lib/js/src/bigarray.js
Including lib/js/src/block.js
Including lib/js/src/buffer.js
Including lib/js/src/bytes.js
Including lib/js/src/bytesLabels.js
Including lib/js/src/callback.js
Including lib/js/src/caml_array.js
Including lib/js/src/caml_array_extern.js
Including lib/js/src/caml_builtin_exceptions.js
Including lib/js/src/caml_bytes.js
Including lib/js/src/caml_bytes_extern.js
Including lib/js/src/caml_char.js
Including lib/js/src/caml_chrome_debugger.js
Including lib/js/src/caml_exceptions.js
Including lib/js/src/caml_external_polyfill.js
Including lib/js/src/caml_float.js
Including lib/js/src/caml_float_extern.js
Including lib/js/src/caml_format.js
Including lib/js/src/caml_gc.js
Including lib/js/src/caml_hash.js
Including lib/js/src/caml_hash_primitive.js
Including lib/js/src/caml_int32.js
Including lib/js/src/caml_int32_extern.js
Including lib/js/src/caml_int64.js
Including lib/js/src/caml_int64_extern.js
Including lib/js/src/caml_io.js
Including lib/js/src/caml_js_exceptions.js
Including lib/js/src/caml_lexer.js
Including lib/js/src/caml_md5.js
Including lib/js/src/caml_module.js
Including lib/js/src/caml_nativeint_extern.js
Including lib/js/src/caml_obj.js
Including lib/js/src/caml_obj_extern.js
Including lib/js/src/caml_oo.js
Including lib/js/src/caml_oo_curry.js
Including lib/js/src/caml_option.js
Including lib/js/src/caml_parser.js
Including lib/js/src/caml_primitive.js
Including lib/js/src/caml_splice_call.js
Including lib/js/src/caml_string.js
Including lib/js/src/caml_string_extern.js
Including lib/js/src/caml_sys.js
Including lib/js/src/caml_undefined_extern.js
Including lib/js/src/caml_utils.js
Including lib/js/src/caml_weak.js
Including lib/js/src/camlinternalBigarray.js
Including lib/js/src/camlinternalFormat.js
Including lib/js/src/camlinternalFormatBasics.js
Including lib/js/src/camlinternalLazy.js
Including lib/js/src/camlinternalMod.js
Including lib/js/src/camlinternalOO.js
Including lib/js/src/char.js
Including lib/js/src/complex.js
Including lib/js/src/curry.js
Including lib/js/src/digest.js
Including lib/js/src/dom.js
Including lib/js/src/dom_storage.js
Including lib/js/src/dom_storage2.js
Including lib/js/src/ephemeron.js
Including lib/js/src/filename.js
Including lib/js/src/format.js
Including lib/js/src/gc.js
Including lib/js/src/genlex.js
Including lib/js/src/hashtbl.js
Including lib/js/src/int32.js
Including lib/js/src/int64.js
Including lib/js/src/js.js
Including lib/js/src/js_array.js
Including lib/js/src/js_array2.js
Including lib/js/src/js_cast.js
Including lib/js/src/js_console.js
Including lib/js/src/js_date.js
Including lib/js/src/js_dict.js
Including lib/js/src/js_exn.js
Including lib/js/src/js_float.js
Including lib/js/src/js_global.js
Including lib/js/src/js_int.js
Including lib/js/src/js_json.js
Including lib/js/src/js_list.js
Including lib/js/src/js_mapperRt.js
Including lib/js/src/js_math.js
Including lib/js/src/js_null.js
Including lib/js/src/js_null_undefined.js
Including lib/js/src/js_obj.js
Including lib/js/src/js_option.js
Including lib/js/src/js_promise.js
Including lib/js/src/js_promise2.js
Including lib/js/src/js_re.js
Including lib/js/src/js_result.js
Including lib/js/src/js_string.js
Including lib/js/src/js_string2.js
Including lib/js/src/js_typed_array.js
Including lib/js/src/js_typed_array2.js
Including lib/js/src/js_types.js
Including lib/js/src/js_undefined.js
Including lib/js/src/js_vector.js
Including lib/js/src/lazy.js
Including lib/js/src/lexing.js
Including lib/js/src/list.js
Including lib/js/src/listLabels.js
Including lib/js/src/map.js
Including lib/js/src/marshal.js
Including lib/js/src/moreLabels.js
Including lib/js/src/nativeint.js
Including lib/js/src/node.js
Including lib/js/src/node_buffer.js
Including lib/js/src/node_child_process.js
Including lib/js/src/node_fs.js
Including lib/js/src/node_fs2.js
Including lib/js/src/node_module.js
Including lib/js/src/node_path.js
Including lib/js/src/node_process.js
Including lib/js/src/obj.js
Including lib/js/src/oo.js
Including lib/js/src/parsing.js
Including lib/js/src/pervasives.js
Including lib/js/src/printexc.js
Including lib/js/src/printf.js
Including lib/js/src/queue.js
Including lib/js/src/random.js
Including lib/js/src/scanf.js
Including lib/js/src/set.js
Including lib/js/src/sort.js
Including lib/js/src/spacetime.js
Including lib/js/src/stack.js
Including lib/js/src/std_exit.js
Including lib/js/src/stdLabels.js
Including lib/js/src/stream.js
Including lib/js/src/string.js
Including lib/js/src/stringLabels.js
Including lib/js/src/sys.js
Including lib/js/src/uchar.js
Including lib/js/src/unix.js
Including lib/js/src/unixLabels.js
Including lib/js/src/weak.js
==== Running for dependencies ====
D:\development\ocaml\spec\interpreter\_build\jslib\temp.js:11
      throw new Error('missing module: ' + name)
      ^

Error: missing module: wasm
    at require (D:\development\ocaml\spec\interpreter\_build\jslib\temp.js:11:13)
    at D:\development\ocaml\spec\interpreter\_build\jslib\temp.js:54430:14
    at Object.<anonymous> (D:\development\ocaml\spec\interpreter\_build\jslib\temp.js:54435:3)
    at Module._compile (internal/modules/cjs/loader.js:738:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:801:12)
    at internal/main/run_main_module.js:21:11
make: *** [Makefile:96: wast.js] Fehler 1
rm _tags
```

**Error: missing module: wasm**

**Comment by CarpeDiemKopi** [comment] 2019-08-14 21:44
I can't find a step where a node module i.e. package wasm is created. 
But it looks like it is required in temp.js.

**Comment by rossberg** [comment] 2019-08-15 13:09
Closing as duplicate of #1052.

**Closed by rossberg** 2019-08-15 13:09 UTC
