### ISSUE TITLE
Uncaught (in promise) RuntimeError: Aborted(CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 44 4f @+0)

### ISSUE THREAD

**Issue by nupur711** [WebAssembly/spec#1410] opened 2022-01-17 12:56 UTC
Getting this error when try to use js file. In the network tab .wasm response has been shown as html file.

**Comment by sbc100** [comment] 2022-01-17 14:22
The found bytes (3c 21 44 4f) as ascii for `<!do` so it looks like you server must serving html rather than that wasm file.  I would use the network tab in devtools to see what is being loading and what the server is returning.

BTW, a web search for "emscripten expected magic word 00 61 73 6d, found 3c 21 44 4f " should be able to find this answer.

**Comment by kripken** [comment] 2022-01-17 17:12
@nupur711 Also the existing advice in https://github.com/WebAssembly/spec/issues/1031, which this is a duplicate of, has more details about how to debug this type of issue.

**Closed by kripken** 2022-01-17 17:12 UTC
