### ISSUE TITLE
question about the "test" module

### ISSUE THREAD

**Issue by zapashcanon** [WebAssembly/spec#1502] opened 2022-07-08 13:15 UTC
Hi,

In some tests (`elem.wasm`, `data.wasm`...) there are some values imported from a `"test"` module. [Example from elem.wast](https://github.com/WebAssembly/spec/blob/main/test/core/elem.wast#L379=):

```wasm
(assert_invalid
  (module
    (global (import "test" "global-i32") i32)
    (table 1 funcref)
    (elem (offset (global.get 0) (global.get 0)))
  )
  "type mismatch"
)
```

I tried to find such a `"test"` module but couldn't find any definition or documentation anywhere. Thus I'm wondering if I really missed it or  if it's indeed not supposed to exist because the various tests referencing it should fail before they actually need it.

If it's the latter, I must admit that I find it quite confusing and I'm wondering if it may not be better to use a real module (I'm thinking of `"spectest"`) ?

**Comment by rossberg** [comment] 2022-07-11 11:48
Technically, it doesn't really matter, because validation happens during compilation, whereas imports are only resolved later, during linking. But I'd be happy accepting a PR that uses a "real" module. ;)

**Comment by rossberg** [comment] 2022-08-04 08:36
Closing as "working as intended".

**Closed by rossberg** 2022-08-04 08:36 UTC
