### ISSUE TITLE
[test] imports.wast unlinkable issue (js-spec)

### ISSUE THREAD

**Issue by Cellule** [WebAssembly/spec#826] opened 2018-06-20 22:20 UTC
In the [imports.wast line:571](https://github.com/WebAssembly/spec/blob/master/test/core/imports.wast#L571) there is the following module
```wast
;; This module is required to validate, regardless of whether it can be
;; linked. Overloading is not possible in wasm itself, but it is possible
;; in modules from which wasm can import.
(assert_unlinkable
  (module
    (import "not wasm" "overloaded" (func))
    (import "not wasm" "overloaded" (func (param i32)))
    (import "not wasm" "overloaded" (func (param i32 i32)))
    (import "not wasm" "overloaded" (func (param i64)))
    (import "not wasm" "overloaded" (func (param f32)))
    (import "not wasm" "overloaded" (func (param f64)))
    (import "not wasm" "overloaded" (func (result i32)))
    (import "not wasm" "overloaded" (func (result i64)))
    (import "not wasm" "overloaded" (func (result f32)))
    (import "not wasm" "overloaded" (func (result f64)))
    (import "not wasm" "overloaded" (global i32))
    (import "not wasm" "overloaded" (global i64))
    (import "not wasm" "overloaded" (global f32))
    (import "not wasm" "overloaded" (global f64))
    (import "not wasm" "overloaded" (table 0 anyfunc))
    (import "not wasm" "overloaded" (memory 0))
  )
  "unknown import"
)
```
The javascript test runner defines `assert_unlinkable` as a test that should throw `WebAssembly.LinkError` when trying to instantiate. (See [spec/js.ml](https://github.com/WebAssembly/spec/blob/d8f775eed3645e689580610d101106cd1404b637/interpreter/script/js.ml#L90))
However, according to the [Javascript Spec](http://webassembly.github.io/spec/js-api/index.html#webassembly-namespace)
```
For each (moduleName, componentName, externtype) in module_imports(module), do
Let o be ? Get(importObject, moduleName).
If Type(o) is not Object, throw a TypeError exception.
```

Since the test runner doesn't provide `not wasm` object, we should throw a TypeError and not a WebAssembly.LinkError.

Providing import `{"not wasm": {}}` would cause a `LinkError` but I'm not sure if that's what we are trying to test here.

**Comment by binji** [comment] 2018-06-26 22:48
@littledan do you have thoughts on the JS behavior here?

**Comment by littledan** [comment] 2018-06-27 01:19
I think the JS semantics were intended here, though @rossberg has stronger opinions than me about the classification of the errors in the Wasm/JS API and could speak better to the original intentions.

To fix this test, @Cellule's suggestion makes sense to me. The comment at the top says that the test is to show that validation passes, which it still would be showing.

IIRC there was a similar other bug in the tests with a missing import, which was resolved similarly; I am not sure where to find it at the moment.

**Comment by rossberg** [comment] 2018-06-27 07:02
This is related to #684. I see three possible fixes, in increasing order of niceness but also intrusiveness:

1. Either change the test so that it uses a known module name (e.g., "spectest" or a module it registers itself).
2. Or change the test runner so that assert_unlinkable allows both a TypeError and a LinkError.
3. Or change the spec to make this a LinkError, too, as @gahaas proposed in #684.

**Comment by rossberg** [comment] 2018-06-27 07:05
PS: Given that it is probably too late for 3 I would suggest 2.

**Comment by littledan** [comment] 2018-06-27 09:22
I'm not sure it's too late for 3; although this code has shipped to the web, I bet it would be web-compatible to change, as lots of error handling code doesn't look at the error type, and also this is a pretty "static" sort of error that's likely to be caught during development rather than due to runtime conditions.

Anyway, 1 and 2 sound like fine options to me.

**Comment by binji** [comment] 2019-01-24 22:13
See https://github.com/WebAssembly/spec/pull/951.

**Comment by binji** [comment] 2019-01-25 16:44
Landed option 1, but I haven't confirmed that this fixes the issue.

**Closed** 2019-05-17 03:13 UTC
